### ISSUE TITLE
Is this obsolete alongside ubuntu-defaults-image

### ISSUE THREAD

**Issue by atkinchris** [nhos-project/live-build-config#1]
I understand from the structure and files in this repo that it's configuration for Debian's `live-build` suite, which (de)bootstraps a live CD (optionally with installer) from scratch.

Is the use of `live-build` and this configuration superseded by `ubuntu-defaults-builder` and the [ubuntu-defaults-image](https://github.com/NHSbuntu/ubuntu-defaults-image) repo?

**Comment by robdyke** [comment]
@atkinchris - Yes. live-build-config is obsolete. This repo really should be archived...

**Comment by robdyke** [comment]
NHSbuntu is now NHoS - see [this post](https://www.openhealthhub.org/t/nhsbuntu-name-change/1211) for detail.

Have a look at the NHoS [ubuntu-defaults-image](https://github.com/nhos-project/ubuntu-defaults-image) repo where you will find our toolchain for producing the ISOs with Docker.

**Comment by atkinchris** [comment]
That makes sense. `ubuntu-defaults-image` is still `live-build` at it's core; guess it just gives you more sugar.

**Comment by robdyke** [comment]
With extra sugar in `ubuntu-defaults-image`

- Support for [packages hosted on packagecloud.io](https://github.com/NHSbuntu/ubuntu-defaults-image/blob/956760e10dec06068d149e983709c4abc7f848c8/ubuntu-defaults-image#L61)
- Support for [extra packages](https://github.com/NHSbuntu/ubuntu-defaults-image/blob/956760e10dec06068d149e983709c4abc7f848c8/ubuntu-defaults-image#L51)
- Adding [HTTPS for apt](https://github.com/NHSbuntu/ubuntu-defaults-image/blob/956760e10dec06068d149e983709c4abc7f848c8/ubuntu-defaults-image#L256) in bootstrap.

Extra extra sugar in `build.sh`

- A wrapper for ubuntu-defaults-image
- Patch to [$LB_ISO_TITLE](https://github.com/NHSbuntu/ubuntu-defaults-image/blob/956760e10dec06068d149e983709c4abc7f848c8/build.sh#L62-L64) which sets .disk/info

And extra extra extra sugar

- Build with [Docker](https://github.com/NHSbuntu/ubuntu-defaults-image/blob/master/Dockerfile)
- Deploy with [Travis](https://github.com/NHSbuntu/ubuntu-defaults-image/blob/master/.travis.yml)

Development focus is now on the [NHoS fork](https://github.com/nhos-project/ubuntu-defaults-image).
